{%- if pillar.keystone.server is defined and pillar.keystone.server.get('enabled') %}
{%- from "keystone/map.jinja" import monitoring with context %}
server:
  target:
    dns:
      enabled: true
      endpoint:
        - name: 'remote_agent_openstack'
          domain:
          - 'tasks.monitoring_remote_agent'
          type: A
          port: '{{ monitoring.output_openstack_port }}'
{%- set major_threshold = monitoring.endpoint_failed_major_threshold|float %}
{% raw %}
  alert:
    KeystoneApiOutage:
      if: >-
        openstack_api_check_status{name=~"keystone.*"} == 0
      labels:
        severity: critical
        service: keystone
      annotations:
        summary: "Keystone API outage"
        description: >-
          Keystone API is not accessible for the Keystone endpoint in the OpenStack service catalog.
    KeystoneApiEndpointDown:
      if: >-
        http_response_status{name=~"keystone.*"} == 0
      for: 2m
      labels:
        severity: minor
        service: keystone
      annotations:
        summary: "{{ $labels.name }} endpoint is not accessible"
        description: >-
          The {{ $labels.name }} endpoint on the {{ $labels.host }} node is not accessible for 2 minutes.
{%- endraw %}
    KeystoneApiEndpointssDownMajor:
      if: >-
        count(http_response_status{name=~"keystone.*"} == 0) by (name) >= count(http_response_status{name=~"keystone.*"}) by (name) * {{ major_threshold }}
      for: 2m
      labels:
        severity: major
        service: keystone
      annotations:
        summary: "{{major_threshold * 100}}{% raw %}% of {{ $labels.name }} endpoints are not accessible"
        description: >-
          {{ $value }} {{ $labels.name }} endpoints (>= {% endraw %}{{major_threshold * 100}}{% raw %}%) are not accessible for 2 minutes.
    KeystoneApiEndpointsOutage:
      if: >-
        count(http_response_status{name=~"keystone.*"} == 0) by (name) == count(http_response_status{name=~"keystone.*"}) by (name)
      for: 2m
      labels:
        severity: critical
        service: keystone
      annotations:
        summary: "{{ $labels.name }} endpoints outage"
        description: >-
          All available {{ $labels.name }} endpoints are not accessible for 2 minutes.
    KeystoneErrorLogsTooHigh:
{%- endraw %}
      {%- set log_threshold = monitoring.error_log_rate|float %}
      if: >-
        sum(rate(log_messages{service="keystone",level=~"(?i:(error|emergency|fatal))"}[5m])) without (level) > {{ log_threshold }}
{%- raw %}
      labels:
        severity: warning
        service: keystone
      annotations:
        summary: "High number of errors in Keystone logs"
        description: "The average per-second rate of errors in Keystone logs on the {{ $labels.host }} node is {{ $value }} (as measured over the last 5 minutes)."
{%- endraw %}
    KeystoneApiResponseTimeTooHigh:
      {%- set response_time_threshold = monitoring.http_response_time_p90|float %}
      if: >-
        max by(host) (openstack_http_response_times{service='keystone',quantile="0.9",http_method=~"^(GET|POST)$",http_status=~"^2..$"}) >= {{ response_time_threshold }}
{%- raw %}
      for: 2m
      labels:
        severity: warning
        service: keystone
      annotations:
        summary: "High response time of Keystone API"
        description: "The Keystone API response time for GET and POST requests on the {{ $labels.host }} node is higher than {% endraw %}{{response_time_threshold}}s for 2 minutes."
{%- endif %}
